// Native module loader for dirsql napi-rs bindings.
// The .node file is generated by `pnpm build` (napi build).
"use strict";

const native = require("./dirsql.node");

/**
 * DirSQL — query a directory as a SQLite database.
 *
 * JavaScript is async by default, so there is a single class (no
 * separate sync/async split).  The constructor kicks off the initial
 * directory scan in a microtask; await `db.ready` before querying.
 *
 * Usage:
 *   const db = new DirSQL(root, tables);
 *   await db.ready;
 *   const rows = db.query("SELECT ...");
 *   for await (const event of db.watch()) { ... }
 */
class DirSQL {
  constructor(root, tables, ignore) {
    this._db = null;
    this._initError = null;

    this.ready = new Promise((resolve) => {
      // Run init in next microtask to be non-blocking
      Promise.resolve().then(() => {
        try {
          this._db = new native.DirSQL(root, tables, ignore);
        } catch (err) {
          this._initError = err;
        }
        resolve();
      });
    }).then(() => {
      if (this._initError !== null) {
        throw this._initError;
      }
    });
  }

  /**
   * Create a DirSQL from a .dirsql.toml config file.
   * Returns a DirSQL instance.  Await `db.ready` before querying.
   */
  static fromConfig(configPath) {
    const instance = Object.create(DirSQL.prototype);
    instance._db = null;
    instance._initError = null;

    instance.ready = new Promise((resolve) => {
      Promise.resolve().then(() => {
        try {
          instance._db = native.DirSQL.fromConfig(configPath);
        } catch (err) {
          instance._initError = err;
        }
        resolve();
      });
    }).then(() => {
      if (instance._initError !== null) {
        throw instance._initError;
      }
    });

    return instance;
  }

  /**
   * Execute a SQL query against the in-memory database.
   */
  query(sql) {
    return this._db.query(sql);
  }

  /**
   * Start watching for file changes.
   * Returns an async iterable of RowEvent objects.
   */
  watch() {
    const db = this._db;
    db.startWatcher();

    return {
      [Symbol.asyncIterator]() {
        let buffer = [];
        return {
          async next() {
            while (true) {
              if (buffer.length > 0) {
                return { value: buffer.shift(), done: false };
              }
              // Poll with a small timeout, then retry
              const events = await new Promise((resolve) => {
                // Use setImmediate/setTimeout to yield to the event loop
                setTimeout(() => {
                  resolve(db.pollEvents(200));
                }, 0);
              });
              if (events.length > 0) {
                buffer.push(...events);
              }
            }
          },
        };
      },
    };
  }
}

// Re-export as a plain object so ESM interop (vitest, etc.) can
// detect named exports. Native addon objects may not be spreadable.
module.exports = { DirSQL };
