// Native module loader for dirsql napi-rs bindings.
// The .node file is generated by `pnpm build` (napi build).
const native = require("./dirsql.node");

// Re-export as a plain object so ESM interop (vitest, etc.) can
// detect named exports. Native addon objects may not be spreadable.
module.exports = { DirSQL: native.DirSQL };
