"""Packaging distcheck flow for the published npm artifact set (#520; was
the per-package `build.test.ts`).

build -> pack -> install -> run: pack the main `dirsql` package and a
reconstructed host `@dirsql/cli-<slug>` sub-package the way the release pipeline
would, `npm install` both into a fresh dir, and run
`node_modules/.bin/dirsql --version`. No mocks -- exactly what `npx dirsql` does
for an end user.

Caveats:
- Tests only the host triple. Cross-triple coverage lives in the release matrix
  (one runner per target).
- The per-platform `package.json` shape is reconstructed here (it is normally
  generated by the release tool), in the shape `src/cli/resolve-binary.ts`
  consumes, so the real launcher resolution path is still exercised.

Effects funnel through an injected `runner` (subprocess.run) and `fs`
(FileSystem); the detected host `Platform` is passed in so each stage is
unit-testable without packing or installing anything.
"""
from __future__ import annotations

import json
import os
import subprocess
from typing import Optional

from distcheck.filesystem import FileSystem
from distcheck.node_flow.platforms import Platform


class DistcheckError(RuntimeError):
    """A distcheck stage failed -- carries a human-readable diagnostic."""


def _require_zero(result, message: str) -> None:
    """Raise `DistcheckError(message)` unless `result` exited 0."""
    if result.returncode != 0:
        raise DistcheckError(message)


def select_tarball(names, prefix: str, exclude: Optional[str] = None) -> str:
    """The single `.tgz` in `names` matching `prefix` (and not `exclude`)."""
    matches = [
        name
        for name in names
        if name.startswith(prefix)
        and name.endswith(".tgz")
        and (exclude is None or not name.startswith(exclude))
    ]
    if len(matches) != 1:
        raise DistcheckError(
            f"expected exactly one {prefix!r} tarball, saw {matches} in {list(names)}"
        )
    (only,) = matches
    return only


def run(
    ts_pkg: str,
    host: Platform,
    *,
    runner=subprocess.run,
    fs: FileSystem = FileSystem(),
) -> int:
    # pnpm build (napi:build + tsc + stage:platform) is a CI prerequisite; the
    # staged host addon is its output. Sanity-check rather than rebuild.
    staged_dir = os.path.join(ts_pkg, "build", host.slug)
    staged_addon = os.path.join(staged_dir, host.addon_name)
    if not fs.exists(staged_addon):
        raise DistcheckError(
            f"prerequisite missing: {staged_addon}. "
            "Run `pnpm build` from packages/ts first."
        )

    staging = fs.mkdtemp("dirsql-distcheck-")

    # 1. Reconstruct + pack the host `@dirsql/lib-<slug>` sub-package -- the
    #    minimum shape `loadNativeCore()` needs to `require` the addon, which
    #    since #739 serves the CLI as well as the SDK.
    cli_pkg_dir = os.path.join(staging, "lib-pkg")
    fs.makedirs(cli_pkg_dir)
    fs.write_text(
        os.path.join(cli_pkg_dir, "package.json"),
        json.dumps(
            {
                "name": host.name,
                "version": "0.0.0-e2e",
                "main": host.addon_name,
                "os": host.os,
                "cpu": host.cpu,
            }
        ),
    )
    packed_addon = os.path.join(cli_pkg_dir, host.addon_name)
    fs.copy(staged_addon, packed_addon)
    fs.chmod(packed_addon, 0o755)

    cli_pack = runner(
        ["npm", "pack", "--pack-destination", staging],
        cwd=cli_pkg_dir,
        capture_output=True,
        text=True,
    )
    _require_zero(cli_pack, f"addon npm pack failed:\n{cli_pack.stdout}\n{cli_pack.stderr}")
    cli_tarball = os.path.join(
        staging, select_tarball(fs.listdir(staging), "dirsql-lib-")
    )

    # 2. Pack the main `dirsql` package through its real `prepack` hook.
    main_pack = runner(
        ["pnpm", "pack", "--pack-destination", staging],
        cwd=ts_pkg,
        capture_output=True,
        text=True,
    )
    _require_zero(
        main_pack, f"main pnpm pack failed:\n{main_pack.stdout}\n{main_pack.stderr}"
    )
    main_tarball = os.path.join(
        staging, select_tarball(fs.listdir(staging), "dirsql-", exclude="dirsql-lib-")
    )

    # 3. Fresh dir, exactly what an end user installs into.
    install_root = fs.mkdtemp("dirsql-distcheck-install-")
    fs.write_text(
        os.path.join(install_root, "package.json"),
        json.dumps({"name": "dirsql-distcheck-host", "version": "0.0.0", "private": True}),
    )
    npm_install = runner(
        ["npm", "install", "--no-audit", "--no-fund", main_tarball, cli_tarball],
        cwd=install_root,
        capture_output=True,
        text=True,
    )
    _require_zero(npm_install, f"npm install failed:\n{npm_install.stderr}")

    # 4. The `dirsql` bin should exist and run the CLI in-process via the addon.
    bin_path = os.path.join(install_root, "node_modules", ".bin", "dirsql")
    if not fs.exists(bin_path):
        raise DistcheckError(f"bin missing at {bin_path}")
    version = runner([bin_path, "--version"], capture_output=True, text=True)
    version_err = (
        f"`dirsql --version` failed; "
        f"stdout={version.stdout!r}, stderr={version.stderr!r}"
    )
    _require_zero(version, version_err)

    # Matching on the word "dirsql" alone let dirsql#958 ship: packages
    # published at 0.4.x printed the embedded core crate's literal (0.2.7).
    installed_main = json.loads(
        fs.read_text(
            os.path.join(install_root, "node_modules", "dirsql", "package.json")
        )
    )
    installed_version = installed_main.get("version")
    if version.stdout.strip() != f"dirsql {installed_version}":
        raise DistcheckError(
            f"`dirsql --version` printed {version.stdout.strip()!r}, expected "
            f"'dirsql {installed_version}' -- the version npm installed. The "
            "launcher (packages/ts/src/cli/main.ts) must read it from its own "
            "package.json and pass it to the addon's `runCli`."
        )

    # 5. Cross-check the published layout: the launcher resolves to a real
    #    addon inside the installed `@dirsql/lib-<slug>` sub-package, and no
    #    standalone-CLI family is installed alongside it (#739).
    cli_pkg_installed = os.path.join(
        install_root, "node_modules", *host.name.split("/")
    )
    if not fs.exists(cli_pkg_installed):
        raise DistcheckError(f"addon sub-pkg missing at {cli_pkg_installed}")
    installed = json.loads(fs.read_text(os.path.join(cli_pkg_installed, "package.json")))
    if installed.get("name") != host.name:
        raise DistcheckError(
            f"addon sub-pkg name mismatch: expected {host.name!r}, saw {installed.get('name')!r}"
        )
    stale_cli = os.path.join(
        install_root, "node_modules", "@dirsql", f"cli-{host.slug}"
    )
    if fs.exists(stale_cli):
        raise DistcheckError(
            f"a standalone-CLI sub-package is still published at {stale_cli}; "
            "the addon carries the CLI since #739, so shipping one would put "
            "a second copy of the core in every install."
        )
    return 0
