"""Packaging distcheck flow for the published npm artifact set (#520; was
the per-package `build.test.ts`).

build -> pack -> install -> run: pack the main `dirsql` package and a
reconstructed host `@dirsql/cli-<slug>` sub-package the way the release pipeline
would, `npm install` both into a fresh dir, and run
`node_modules/.bin/dirsql --version`. No mocks -- exactly what `npx dirsql` does
for an end user.

Caveats:
- Tests only the host triple. Cross-triple coverage lives in the release matrix
  (one runner per target).
- The per-platform `package.json` shape is reconstructed here (it is normally
  generated by the release tool), in the shape `src/cli/resolve-binary.ts`
  consumes, so the real launcher resolution path is still exercised.

Effects funnel through an injected `runner` (subprocess.run) and `fs`
(FileSystem); the detected host `Platform` is passed in so each stage is
unit-testable without packing or installing anything.
"""
from __future__ import annotations

import json
import os
import subprocess
from typing import Optional

from distcheck.filesystem import FileSystem
from distcheck.node_flow.platforms import Platform


class DistcheckError(RuntimeError):
    """A distcheck stage failed -- carries a human-readable diagnostic."""


def _require_zero(result, message: str) -> None:
    """Raise `DistcheckError(message)` unless `result` exited 0."""
    if result.returncode != 0:
        raise DistcheckError(message)


def select_tarball(names, prefix: str, exclude: Optional[str] = None) -> str:
    """The single `.tgz` in `names` matching `prefix` (and not `exclude`)."""
    matches = [
        name
        for name in names
        if name.startswith(prefix)
        and name.endswith(".tgz")
        and (exclude is None or not name.startswith(exclude))
    ]
    if len(matches) != 1:
        raise DistcheckError(
            f"expected exactly one {prefix!r} tarball, saw {matches} in {list(names)}"
        )
    (only,) = matches
    return only


def run(
    ts_pkg: str,
    host: Platform,
    *,
    runner=subprocess.run,
    fs: FileSystem = FileSystem(),
) -> int:
    # pnpm build (napi:build + tsc + stage:platform) is a CI prerequisite; the
    # staged host CLI binary is its output. Sanity-check rather than rebuild.
    staged_cli = os.path.join(ts_pkg, "build", f"bundled-cli-{host.slug}")
    staged_binary = os.path.join(staged_cli, host.bin_name)
    if not fs.exists(staged_binary):
        raise DistcheckError(
            f"prerequisite missing: {staged_binary}. "
            "Run `pnpm build` from packages/ts first."
        )

    staging = fs.mkdtemp("dirsql-distcheck-")

    # 1. Reconstruct + pack the host `@dirsql/cli-<slug>` sub-package -- the
    #    minimum shape the launcher's `require.resolve('<pkg>/dirsql')` needs.
    cli_pkg_dir = os.path.join(staging, "cli-pkg")
    fs.makedirs(cli_pkg_dir)
    fs.write_text(
        os.path.join(cli_pkg_dir, "package.json"),
        json.dumps(
            {
                "name": host.name,
                "version": "0.0.0-e2e",
                "os": host.os,
                "cpu": host.cpu,
            }
        ),
    )
    packed_binary = os.path.join(cli_pkg_dir, host.bin_name)
    fs.copy(staged_binary, packed_binary)
    fs.chmod(packed_binary, 0o755)

    cli_pack = runner(
        ["npm", "pack", "--pack-destination", staging],
        cwd=cli_pkg_dir,
        capture_output=True,
        text=True,
    )
    _require_zero(cli_pack, f"cli npm pack failed:\n{cli_pack.stdout}\n{cli_pack.stderr}")
    cli_tarball = os.path.join(
        staging, select_tarball(fs.listdir(staging), "dirsql-cli-")
    )

    # 2. Pack the main `dirsql` package through its real `prepack` hook.
    main_pack = runner(
        ["pnpm", "pack", "--pack-destination", staging],
        cwd=ts_pkg,
        capture_output=True,
        text=True,
    )
    _require_zero(
        main_pack, f"main pnpm pack failed:\n{main_pack.stdout}\n{main_pack.stderr}"
    )
    main_tarball = os.path.join(
        staging, select_tarball(fs.listdir(staging), "dirsql-", exclude="dirsql-cli-")
    )

    # 3. Fresh dir, exactly what an end user installs into.
    install_root = fs.mkdtemp("dirsql-distcheck-install-")
    fs.write_text(
        os.path.join(install_root, "package.json"),
        json.dumps({"name": "dirsql-distcheck-host", "version": "0.0.0", "private": True}),
    )
    npm_install = runner(
        ["npm", "install", "--no-audit", "--no-fund", main_tarball, cli_tarball],
        cwd=install_root,
        capture_output=True,
        text=True,
    )
    _require_zero(npm_install, f"npm install failed:\n{npm_install.stderr}")

    # 4. The `dirsql` bin should exist and execute against the bundled binary.
    bin_path = os.path.join(install_root, "node_modules", ".bin", "dirsql")
    if not fs.exists(bin_path):
        raise DistcheckError(f"bin missing at {bin_path}")
    version = runner([bin_path, "--version"], capture_output=True, text=True)
    version_err = (
        f"`dirsql --version` failed; "
        f"stdout={version.stdout!r}, stderr={version.stderr!r}"
    )
    _require_zero(version, version_err)
    if "dirsql" not in version.stdout:
        raise DistcheckError(version_err)

    # 5. Cross-check the published layout: the launcher resolves to a real
    #    binary inside the installed `@dirsql/cli-<slug>` sub-package.
    cli_pkg_installed = os.path.join(
        install_root, "node_modules", *host.name.split("/")
    )
    if not fs.exists(cli_pkg_installed):
        raise DistcheckError(f"cli sub-pkg missing at {cli_pkg_installed}")
    installed = json.loads(fs.read_text(os.path.join(cli_pkg_installed, "package.json")))
    if installed.get("name") != host.name:
        raise DistcheckError(
            f"cli sub-pkg name mismatch: expected {host.name!r}, saw {installed.get('name')!r}"
        )
    return 0
