// Native module loader for dirsql napi-rs bindings.
// The .node file is generated by `pnpm build` (napi build).

export interface TableDef {
  /** SQL DDL statement (e.g., "CREATE TABLE users (name TEXT, age INTEGER)") */
  ddl: string;
  /** Glob pattern for matching files to this table */
  glob: string;
  /** Function to extract rows from a file */
  extract: (filePath: string, content: string) => Record<string, unknown>[];
  /** If true, reject rows with columns not in the DDL */
  strict?: boolean;
}

export interface RowEvent {
  table: string;
  action: "insert" | "update" | "delete" | "error";
  row?: Record<string, unknown> | null;
  oldRow?: Record<string, unknown> | null;
  error?: string | null;
  filePath?: string | null;
}

// The native addon exposes a DirSQL class. We load it and re-export
// with proper TypeScript types.
// eslint-disable-next-line @typescript-eslint/no-var-requires
interface NativeDirSQLInstance {
  query(sql: string): Record<string, unknown>[];
  startWatcher(): void;
  pollEvents(timeoutMs: number): RowEvent[];
}

interface NativeDirSQLConstructor {
  new (
    root: string,
    tables: TableDef[],
    ignore?: string[],
  ): NativeDirSQLInstance;
}

const native: { DirSQL: NativeDirSQLConstructor } = require("../dirsql.node");

export const DirSQL: {
  new (root: string, tables: TableDef[], ignore?: string[]): DirSQL;
} = native.DirSQL as unknown as {
  new (root: string, tables: TableDef[], ignore?: string[]): DirSQL;
};

export interface DirSQL {
  /**
   * Execute a SQL query against the in-memory database.
   *
   * @param sql - SQL query string
   * @returns Array of row objects
   */
  query(sql: string): Record<string, unknown>[];

  /**
   * Start the file watcher. Must be called before pollEvents.
   */
  startWatcher(): void;

  /**
   * Poll for file change events.
   *
   * @param timeoutMs - Timeout in milliseconds to wait for events
   * @returns Array of row events (may be empty if no changes within timeout)
   */
  pollEvents(timeoutMs: number): RowEvent[];
}
