// Packaging smoke test: build -> pack -> install -> run the published npm
// artifact set. Packs the main `dirsql` package, constructs a host-platform
// `@dirsql/cli-<slug>` package the way the release pipeline would, installs
// both into a fresh temp dir with `npm install`, and runs
// `node_modules/.bin/dirsql --version`. No mocks -- exactly what
// `npx dirsql` does for an end user.
//
// Caveats:
// - Tests only the host triple. Cross-triple coverage lives in the
//   release matrix (one runner per target).
// - The per-platform `package.json` shape is reconstructed locally (it is
//   normally generated by the release tool), in the shape
//   `src/cli/resolve-binary.ts` consumes, so the real launcher resolution
//   path is still exercised.

import { spawnSync } from "node:child_process";
import {
  chmod,
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { librarySlug } from "../../src/platforms.js";
import { findHostPlatform } from "../../tools/stage-platform.js";
import { exists } from "../exists.js";

const TS_PKG = resolve(fileURLToPath(import.meta.url), "..", "..", "..");
const REPO = resolve(TS_PKG, "..", "..");

interface BuiltArtifacts {
  mainTarball: string;
  cliTarball: string;
  cliPackageName: string;
}

let artifacts: BuiltArtifacts;

beforeAll(async () => {
  // pnpm build runs napi:build + tsc + stage:platform. We rely on it
  // having been run by the CI job before this test (the wireit task
  // graph caches it across runs locally). Sanity-check the outputs are
  // present rather than re-running the whole build inside the test.
  const host = findHostPlatform();
  const slug = librarySlug(host);
  const stagedCli = join(TS_PKG, "build", `bundled-cli-${slug}`);
  const binName = host.exe === true ? "dirsql.exe" : "dirsql";
  const stagedBinary = join(stagedCli, binName);
  if (!(await exists(stagedBinary))) {
    throw new Error(
      `prerequisite missing: ${stagedBinary}. Run \`pnpm build\` from packages/ts before this test.`,
    );
  }

  const stagingRoot = await mkdtemp(join(tmpdir(), "dirsql-e2e-"));

  // 1. Pack the host platform's `@dirsql/cli-<slug>` package. In the
  //    real release flow this is produced and published by the release
  //    tool; here we reconstruct the minimum shape that the launcher's
  //    `require.resolve('<pkg>/dirsql')` needs.
  const cliPkgDir = join(stagingRoot, "cli-pkg");
  await mkdir(cliPkgDir, { recursive: true });
  const cliPkgJson = {
    name: host.name,
    version: "0.0.0-e2e",
    os: host.os,
    cpu: host.cpu,
  };
  await writeFile(
    join(cliPkgDir, "package.json"),
    JSON.stringify(cliPkgJson, null, 2),
  );
  await copyFile(stagedBinary, join(cliPkgDir, binName));
  await chmod(join(cliPkgDir, binName), 0o755);

  const cliPack = spawnSync(
    "npm",
    ["pack", "--pack-destination", stagingRoot],
    {
      cwd: cliPkgDir,
      encoding: "utf8",
    },
  );
  if (cliPack.status !== 0) {
    throw new Error(`cli npm pack failed: ${cliPack.stderr || cliPack.stdout}`);
  }
  const cliTarball = (await readdir(stagingRoot))
    .filter((f) => f.startsWith("dirsql-cli-") && f.endsWith(".tgz"))
    .map((f) => join(stagingRoot, f))[0];
  if (!cliTarball) {
    throw new Error(
      `cli npm pack produced no tarball in ${stagingRoot} (saw ${(await readdir(stagingRoot)).join(", ")})`,
    );
  }

  // 2. Pack the main `dirsql` package. This goes through the package's
  //    real `prepack` hook (stageDocs).
  const mainPack = spawnSync(
    "pnpm",
    ["pack", "--pack-destination", stagingRoot],
    { cwd: TS_PKG, encoding: "utf8" },
  );
  if (mainPack.status !== 0) {
    throw new Error(
      `main pnpm pack failed: ${mainPack.stderr || mainPack.stdout}`,
    );
  }
  const mainTarball = (await readdir(stagingRoot))
    .filter(
      (f) =>
        f.startsWith("dirsql-") &&
        !f.startsWith("dirsql-cli-") &&
        f.endsWith(".tgz"),
    )
    .map((f) => join(stagingRoot, f))[0];
  if (!mainTarball) {
    throw new Error(
      `main pnpm pack produced no tarball in ${stagingRoot} (saw ${(await readdir(stagingRoot)).join(", ")})`,
    );
  }

  artifacts = {
    mainTarball,
    cliTarball,
    cliPackageName: host.name,
  };
});

describe("npm-installed dirsql CLI", () => {
  it("registers a `dirsql` bin script that execs the bundled binary", async () => {
    const installRoot = await mkdtemp(join(tmpdir(), "dirsql-e2e-install-"));
    await writeFile(
      join(installRoot, "package.json"),
      JSON.stringify({
        name: "dirsql-e2e-host",
        version: "0.0.0",
        private: true,
      }),
    );

    const npmInstall = spawnSync(
      "npm",
      [
        "install",
        "--no-audit",
        "--no-fund",
        artifacts.mainTarball,
        artifacts.cliTarball,
      ],
      { cwd: installRoot, encoding: "utf8" },
    );
    expect(npmInstall.status, npmInstall.stderr).toBe(0);

    // 3. The `dirsql` bin should exist and execute against the
    //    cargo-built binary.
    const binPath = join(installRoot, "node_modules", ".bin", "dirsql");
    expect(await exists(binPath), `bin missing at ${binPath}`).toBe(true);

    const result = spawnSync(binPath, ["--version"], { encoding: "utf8" });
    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toMatch(/dirsql/);

    // 4. Cross-check the published package layout: the launcher should
    //    resolve to a real binary inside @dirsql/cli-<slug>.
    const cliPkgDir = join(
      installRoot,
      "node_modules",
      artifacts.cliPackageName,
    );
    expect(await exists(cliPkgDir), `cli sub-pkg missing at ${cliPkgDir}`).toBe(
      true,
    );
    const cliPkgJson = JSON.parse(
      await readFile(join(cliPkgDir, "package.json"), "utf8"),
    );
    expect(cliPkgJson.name).toBe(artifacts.cliPackageName);
  });
});
